INSERT INTO users (name) VALUES ('John Bob');
INSERT INTO users (name) VALUES ('Mary Li');
INSERT INTO users (name) VALUES ('Josh Miller');
INSERT INTO users (name) VALUES ('Angela Martin');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('dry thyme', 1, 2049, 5, 'tablespoon', 'thyme.jpg');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('parmesan cheese', 1, 1033, 0.01, 'kg', 'parmesan.png');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('low fat american cheese', 1, 1253, 1, 'slices', 'american-cheese.png');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('milk', 1, 1077, 12, 'tablespoon', 'milk.png');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('banana', 1, 9040, 2, '', 'banana.jpg');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('tomato', 1, 11529, 5, '', 'banana.jpg');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('spaghettini', 1, 12520420, 500, 'grams', 'banana.jpg');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('chocolate milk', 2, 1102, 100, 'ml', 'banana.jpg');
INSERT INTO pantry_ingredients (item_name, user_id, spoonacular_ingredient_id, quantity, measure, image_link) VALUES ('eggs', 2, 1123, 12, '', 'banana.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Steak And Pepper Rounds With Rose Horseradish Garlic Creme Sauce','monday', 1, 661500, 'breakfast', 1, 'https://spoonacular.com/recipeImages/661500-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Falafel Burger', 'monday', 1, 642539, 'lunch', 1, 'https://spoonacular.com/recipeImages/642539-312x231.png');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Steak Salad with Chimichurri Sauce','monday', 1, 1096025, 'dinner', 1, 'https://spoonacular.com/recipeImages/1096025-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('$50,000 Burger','tuesday', 1, 631814, 'breakfast', 1, 'https://spoonacular.com/recipeImages/631814-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Cassoulet for 10','tuesday', 1, 637275, 'lunch', 1, 'https://spoonacular.com/recipeImages/637275-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Cake Mix Donuts','tuesday', 1, 636078, 'dinner', 1, 'https://spoonacular.com/recipeImages/633876-556x370.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Salad With Apples, Gorgonzola and Walnuts','wednesday', 1, 659015, 'breakfast', 1, 'https://spoonacular.com/recipeImages/659015-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Egg Salad Sandwiches With Tarragon','wednesday', 1, 642240, 'lunch', 1, 'https://spoonacular.com/recipeImages/642240-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Crab Salad in Avocado Boats','wednesday', 1, 640311, 'dinner', 1, 'https://spoonacular.com/recipeImages/640311-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('French Dips With Au Jus','thursday', 1, 643330, 'breakfast', 1, 'https://spoonacular.com/recipeImages/643330-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Broccoli Soup','thursday', 1, 1096263, 'lunch', 1, 'https://spoonacular.com/recipeImages/1096263-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Chinese Bbq Pork Ribs','thursday', 1, 638631, 'dinner', 1, 'https://spoonacular.com/recipeImages/638631-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Italian Fig Cookies','friday', 1, 648119, 'breakfast', 1, 'https://spoonacular.com/recipeImages/648119-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('French Onion Marsala Soup','friday', 1, 643362, 'lunch', 1, 'https://spoonacular.com/recipeImages/643362-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Italian Seafood Stew','friday', 1, 648247, 'dinner', 1, 'https://spoonacular.com/recipeImages/648247-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Fourth Of July Sourdough Pancakes','saturday', 1, 643249, 'breakfast', 1, 'https://spoonacular.com/recipeImages/643249-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Hot and sour noodle soup','saturday', 1, 647372, 'lunch', 1, 'https://spoonacular.com/recipeImages/647372-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('French Style Almond Saffron Cake','saturday', 1, 643400, 'dinner', 1, 'https://spoonacular.com/recipeImages/643400-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Oh My Ganache','sunday', 1, 653520, 'breakfast', 1, 'https://spoonacular.com/recipeImages/653520-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Japanese Curry Puffs','sunday', 1, 648470, 'lunch', 1, 'https://spoonacular.com/recipeImages/648470-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Chinese Veg Fried rice','sunday', 1, 638729, 'dinner', 1, 'https://spoonacular.com/recipeImages/638729-312x231.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('A Meal','wednesday', 1, 654830, 'lunch', 2, 'https://spoonacular.com/recipeImages/633876-556x370.jpg');
INSERT INTO meal_lists (meal_name, day_of_week, user_id, spoonacular_id, meal, week, image_link) VALUES ('Steak with lemon and capers','tuesday', 2, 661531, 'breakfast', 2, 'https://spoonacular.com/recipeImages/661531-312x231.jpg');
INSERT INTO favourites (user_id, spoonacular_id) VALUES (1, 663641);
INSERT INTO favourites (user_id, spoonacular_id) VALUES (1, 636078);
INSERT INTO favourites (user_id, spoonacular_id) VALUES (1, 646545);
INSERT INTO jokes (joke) VALUES ('Any salad can be a Caesar salad if you stab it enough.');
INSERT INTO jokes (joke) VALUES ('What does a nosey pepper do? Gets jalapeno business.');
INSERT INTO jokes (joke) VALUES ('What do you call a fake noodle? An impasta.');
INSERT INTO jokes (joke) VALUES ('Why couldn’t the sesame seed leave the gambling casino? Because he was on a roll.');
INSERT INTO jokes (joke) VALUES ('What’s orange and sounds like a parrot? A carrot.');
INSERT INTO jokes (joke) VALUES ('When potatoes have babies, what are they called? Tater tots.');
INSERT INTO jokes (joke) VALUES ('How fast is milk? It’s pasteurized before you know it.');
INSERT INTO jokes (joke) VALUES ('How do you make an apple turnover? Push it downhill.');
INSERT INTO jokes (joke) VALUES ('What’s better than a good friend? A good friend with chocolate.');
INSERT INTO jokes (joke) VALUES ('What kind of socks do you need to plant asparagus? Garden hose.');
INSERT INTO jokes (joke) VALUES ('What did the pecan say to the walnut? We’re friends because we’re both nuts.');
INSERT INTO jokes (joke) VALUES ('Why did the skeleton go to the barbecue? To get another rib.');
INSERT INTO jokes (joke) VALUES ('Where did the broccoli go to have a few drinks? The salad bar.');
INSERT INTO jokes (joke) VALUES ('What did one blueberry say to the other blueberry? If you weren’t so sweet, we wouldn’t be in this jam.');
INSERT INTO jokes (joke) VALUES ('What do you call cheese that is not yours? Nacho cheese.');
INSERT INTO jokes (joke) VALUES ('Wanna hear a joke about pizza? Never mind it’s too cheesy.');
INSERT INTO jokes (joke) VALUES ('What is a tree’s favorite soda? Root Beer.');
INSERT INTO jokes (joke) VALUES ('Did you hear how they caught the great produce bandit? He stopped to take a leek.');
INSERT INTO jokes (joke) VALUES ('Which dessert is perfect for eating in bed? A sheet cake.');
INSERT INTO jokes (joke) VALUES ('What happened after an explosion at a French cheese factory? All that was left was de brie.');
INSERT INTO jokes (joke) VALUES ('Why did the butcher work extra hours at the shop? To make ends meat.');
INSERT INTO jokes (joke) VALUES ('Who''s a dessert''s favorite actor? Robert Brownie Jr.');
INSERT INTO jokes (joke) VALUES ('When do you go at red and stop at green? When you’re eating a watermelon.');
INSERT INTO jokes (joke) VALUES ('What do you call cheese that is sad? Blue cheese.');
INSERT INTO jokes (joke) VALUES ('What do you call blueberries playing the guitar? A jam session.');
INSERT INTO jokes (joke) VALUES ('Did you hear about the carrot detective? He got to the root of every case.');
INSERT INTO jokes (joke) VALUES ('What do you get if you cross an apple with a shellfish? A crab apple!');
INSERT INTO jokes (joke) VALUES ('Did you see the movie about the hot dog? It was an Oscar wiener.');
INSERT INTO jokes (joke) VALUES ('What''s the difference between a shamrock and a bread knife that gets used a lot? The shamrock is a four-leaf clover, and the knife is a four-loaf cleaver.');
INSERT INTO jokes (joke) VALUES ('What did the hot dog say when his friend passed him in the race? Wow, I relish the fact that you''ve mustard the strength to ketchup to me.');
INSERT INTO jokes (joke) VALUES ('Which thrill ride does a wine glass love to go on the most? A coaster!');
INSERT INTO jokes (joke) VALUES ('How do you keep intruders out of a castle made of cheese? Moatzarella.');
INSERT INTO jokes (joke) VALUES ('Which type of vegetable tries to be cool, but is only partly successful at it? The radish.');
INSERT INTO jokes (joke) VALUES ('What do you call a round, green vegetable that breaks out of prison? An escapea.');
INSERT INTO jokes (joke) VALUES ('Why did the dieter go to the paint store? They wanted to get thinner.');
INSERT INTO jokes (joke) VALUES ('What does a grape say when it gets stepped on? Nothing, it just lets out a little wine.');
INSERT INTO jokes (joke) VALUES ('Boy, I just got hit in the head with a can of soda. I was lucky it was a soft drink.');
INSERT INTO jokes (joke) VALUES ('What do you get when you play Tug-of-War with a pig? Pulled-Pork.');
INSERT INTO jokes (joke) VALUES ('It was an emotional wedding. Even the cake was in tiers.');
INSERT INTO jokes (joke) VALUES ('What do you call the king of vegetables? Elvis Parsley.');
INSERT INTO jokes (joke) VALUES ('You know what’s hard to beat for breakfast? A boiled egg.');
INSERT INTO jokes (joke) VALUES ('Spending a lot of time at the coffee bar can cause a latte problems.');
INSERT INTO jokes (joke) VALUES ('I was going to grow an herb garden, but I couldn’t find the thyme.');
INSERT INTO jokes (joke) VALUES ('The majority of Americans find bananas a peeling.');
INSERT INTO jokes (joke) VALUES ('The price of candy at the movie theater is ridiculous. They''re always raisinet!');
INSERT INTO jokes (joke) VALUES ('I love when candy canes are in mint condition.');
INSERT INTO jokes (joke) VALUES ('Becoming a vegetarian was a huge missed steak.');
INSERT INTO jokes (joke) VALUES ('What are hot dogs called in winter? Chilly dogs.');
INSERT INTO jokes (joke) VALUES ('Time flies like an arrow. Fruit flies like a banana.');
INSERT INTO jokes (joke) VALUES ('Why did the tomato blush? Because it saw the salad dressing.');
INSERT INTO jokes (joke) VALUES ('Did you hear the one about the greedy peanut butter? I''m not telling you. You might spread it.');
INSERT INTO jokes (joke) VALUES ('A lot of people cry when they cut onions. The trick is not to form an emotional bond.');
INSERT INTO jokes (joke) VALUES ('Why shouldn''t you tell a secret on a farm? Because the potatoes have eyes and the corn has ears.');
INSERT INTO jokes (joke) VALUES ('Why do hamburgers go to the gym? To get better buns.');
INSERT INTO jokes (joke) VALUES ('I wrote a song about a tortilla. Well actually, it’s more of a wrap.');
INSERT INTO jokes (joke) VALUES ('Why did the apricot ask a prune to dinner? Because he couldn''t find a date.');
INSERT INTO jokes (joke) VALUES ('What do you get from a pampered cow? Spoiled milk.');
INSERT INTO jokes (joke) VALUES ('How much room should you give fungi to grow? As mushroom as possible.');
